import * as images from "../images/Images" 

export const products = [
  { title: "Burger X100", price: 500, image: images.burger },
  { title: "Coca-Cola X100", price: 200, image: images.cocacola },
  { title: "iPhone", price: 1000, image: images.iPhone },
  { title: "Tesla Model S", price: 90000, image: images.tesla },
  { title: "Rocket", price: 150000000, image: images.rocket },
  { title: "Island in the Caribbean", price: 50_000_000, image: images.island },
  { title: "Private Jet", price: 70_000_000, image: images.jet },
  { title: "Yacht", price: 120_000_000, image: images.yacht },
  { title: "Super Bowl Ad", price: 7_000_000, image: images.superbowl },
  { title: "Hollywood Movie Budget", price: 200_000_000, image: images.hollywood },
  { title: "Lamborghini", price: 400_000, image: images.lamborghini },
  { title: "Apartment in NYC", price: 1_500_000, image: images.apartment },
  { title: "Bugatti Chiron", price: 3_000_000, image: images.bugatti },
  { title: "Gold Toilet", price: 5_000_000, image: images.goldToilet },
  { title: "Underwater Hotel Night", price: 150_000, image: images.underwaterHotel },
  { title: "Buy a Tank (M1 Abrams)", price: 9_000_000, image: images.tank },
  { title: "F1 Team Sponsorship", price: 50_000_000, image: images.f1 },
  { title: "Rent Eiffel Tower for a day", price: 1_000_000, image: images.eiffel },
  { title: "Buy 1 Million Avocados", price: 2_000_000, image: images.avocados },
  { title: "Luxury Space Cruise", price: 2_500_000, image: images.spaceCruise },
  { title: "NFT Art Piece", price: 1_000_000, image: images.nft },
  { title: "Own a Football Stadium", price: 1_200_000_000, image: images.stadium },
  { title: "Castle in Scotland", price: 25_000_000, image: images.castle },
  { title: "Diamond-Encrusted Watch", price: 2_000_000, image: images.diamondWatch },
  { title: "Fly to Edge of Space", price: 250_000, image: images.edgeOfSpace },
  { title: "Underwater Mansion", price: 90_000_000, image: images.underwaterMansion },
  {
    title: "Fund the budget of the poorest country",
    price: 3_000_000_000,
    image: images.burundi,
  },
  {
    title: "Buy all the books in the world",
    price: 100_000_000_000,
    image: images.books,
    unique: true,
  },
  {
    title: "Build and demolish a skyscraper",
    price: 2_000_000_000,
    image: images.skyscraper,
  },
  {
    title: "Flatten a 100 km² hole",
    price: 1_500_000_000,
    image: images.flattenHole,
  },
  {
    title: "Build a house on the Moon",
    price: 10_000_000_000,
    image: images.moonHouse,
    music: true,
  },
  {
    title: "Replace Dubai roads with gold",
    price: 30_000_000_000,
    image: images.dubaiRoads,
    unique: true,
  },
  {
    title: "Print 1 billion 'You're awesome' postcards",
    price: 50_000_000,
    image: images.postcards,
  },
  {
    title: "Give iPhones to everyone in Kazakhstan",
    price: 50_000_000_000,
    image: images.kazakhstanIphones,
    unique: true,
  },
  {
    title: "Drop candy from 1000 drones over Africa",
    price: 25_000_000,
    image: images.candyDrones,
  },
  {
    title: "Create the world's largest pizza (100 meters)",
    price: 2_000_000,
    image: images.pizza,
  },
];
